ARG BASE_IMAGE="${BASE_IMAGE:-debian:stable-slim}"
FROM ${BASE_IMAGE} AS base

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update

RUN apt-get -y install \
    ca-certificates \
    bash \
    curl \
    libcurl4-openssl-dev \
    net-tools \
    iproute2 \
    grep \
    git \
    build-essential \
    meson \
    pkg-config \
    cmake \
    libexpat1-dev \
    libmicrohttpd-dev \
    libjsoncpp-dev \
    libmpdclient-dev

# create build directory
WORKDIR /build

# build npupnp
RUN git clone https://framagit.org/medoc92/npupnp.git
WORKDIR /build/npupnp
RUN meson setup --prefix /usr build
WORKDIR /build/npupnp/build
RUN ninja
RUN meson install

# build libupnpp
WORKDIR /build
RUN git clone https://framagit.org/medoc92/libupnpp.git
WORKDIR /build/libupnpp
RUN meson setup --prefix /usr build
WORKDIR /build/libupnpp/build
RUN ninja
RUN meson install

# leave build dependencies or remove? This is the question.
RUN apt-get -y remove pkg-config meson cmake build-essential libexpat1-dev
RUN apt-get -y autoremove
RUN	rm -Rf /var/lib/apt/lists/*
RUN rm -Rf /build

FROM scratch
COPY --from=base / /

LABEL maintainer="GioF71"
LABEL source="https://github.com/GioF71/upmpdcli-docker"

ENTRYPOINT ["/bin/sh"]
