name: Publish multi-arch Docker images

on:
  push:
    branches:
      - main
      - devel

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base: ["jammy"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Release Tag
        run: |
          declare -A base_image_from_matrix

          base_image_from_matrix[focal]=ubuntu:focal
          base_image_from_matrix[jammy]=ubuntu:jammy

          # set default base image
          select_base_image=base_image_from_matrix[jammy]

          if [ -v base_image_from_matrix[${{ matrix.base }}] ]; then
            select_base_image=base_image_from_matrix[${{ matrix.base }}]
          fi
          echo "Select Base Image [" $select_base_image "]"

          echo "GITHUB_REF_NAME = ["${{ env.GITHUB_REF_NAME }}"]"
          prefix=""
          if [ "$env.GITHUB_REF_NAME" = "devel" ]; then
            prefix = "dev-"
          fi
          date=$(TZ=Europe/Rome date '+%Y-%m-%d')
          base=${{ matrix.base }}
          upmpdcli_version="upmpdcli-1.5.20-libupnpp-0.22.2"
          image_name="${{secrets.DOCKER_USERNAME}}/upmpdcli"
          full="${upmpdcli_version}-${base}-${date}"
          version_and_base="${upmpdcli_version}-${base}"
          if [ "$env.GITHUB_REF_NAME" = "devel" ]; then
            tags="${image_name}:dev-${base}-${date}
          else
            tags="${image_name}:${base},${image_name}:${version_and_base},${image_name}:${full},${image_name}:latest,${image_name}:stable"
          fi
          echo "RELEASE_TAGS=${tags}" >> $GITHUB_ENV
          echo "BASE_IMAGE=${select_base_image}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ matrix.base }}
            USE_APT_PROXY=N
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: ${{ env.RELEASE_TAGS }}
