name: Publish multi-arch Docker images

on:
  push:
    tags:
      - "release/*"
      - "main/*"
      - "devel/*"
      - "feature/*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base: ["jammy", "focal"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare for Docker Build
        run: |
          ref_type=${{ github.ref_type }}
          echo "REF_TYPE: ["$ref_type"]"

          ref_name=${{ github.ref_name }}
          echo "REF_NAME: ["$ref_name"]"

          ref=${{ github.ref }}
          echo "REF: ["$ref"]"

          declare -A base_images
          base_images[jammy]=ubuntu:jammy
          base_images[focal]=ubuntu:focal

          stable="jammy"
          latest="jammy"

          tag_stable="stable"
          tag_latest="latest"

          declare -A upmpdcli_versions
          upmpdcli_versions[jammy]=1.5.19
          upmpdcli_versions[focal]=1.5.19

          declare -A libupnp_versions
          libupnp_versions[jammy]=0.22.2
          libupnp_versions[focal]=0.22.2

          base=${{ matrix.base }}
          select_base_image=${base_images[$base]}
          echo "select_base_image=["$select_base_image"]"

          select_upmpdcli_version=${upmpdcli_versions[$base]}
          select_libupnp_version=${libupnp_versions[$base]}

          upmpdcli_version="upmpdcli-$select_upmpdcli_version-libupnpp-$select_libupnp_version"
          image_name="${{secrets.DOCKER_USERNAME}}/upmpdcli"

          echo "image_name=["$image_name"]"
          echo "upmpdcli_version=["$upmpdcli_version"]"

          tags=""
          if [ "${ref_type}" = "branch" ]; then
            echo "branch mode";
            if [ "${ref_name}" = "main" ]; then
              echo "main branch";
              tags="${image_name}:main-${base}";
              main_date=$(TZ=Europe/Rome date '+%Y-%m-%d')
              tags="$tags,${image_name}:main-${base}-${main_date}";
              tags="$tags,${image_name}:main-${base}-${upmpdcli_version}";
              tags="$tags,${image_name}:main-${base}-${upmpdcli_version}-${select_date}";
            elif [ "${ref_name}" = "devel" ]; then
              echo "devel branch";
              devel_timestamp=$(TZ=Europe/Rome date '+%Y-%m-%d-%H-%M-%S')
              tags="${image_name}:devel-${base},${image_name}:devel-${base}-${devel_timestamp}";
            else
              echo "other branch ["${ref_name}"]";
              other_timestamp=$(TZ=Europe/Rome date '+%Y-%m-%d-%H-%M-%S')
              tags="${image_name}:${ref_name}-${base}-${other_timestamp}";
            fi
          elif [ "${ref_type}" = "tag" ]; then
            echo "tag mode";
            echo "tag is ["${ref_name}"]";

            tag_type=$(echo ${ref_name} | cut -d '/' -f 1)
            tag_name=$(echo ${ref_name} | cut -d '/' -f 2) 

            release=${tag_name}

            if [ "${tag_type}" = "release" ]; then
              echo "release tag";
              tags="${image_name}:${base}";
              tags="$tags,${image_name}:${base}-${release}";
              tags="$tags,${image_name}:${base}-${upmpdcli_version}";
              tags="$tags,${image_name}:${base}-${upmpdcli_version}-${release}";
              if [ "${base}" = "${latest}" ]; then
                tags="$tags,${image_name}:${tag_latest}";
              fi
              if [ "${base}" = "${stable}" ]; then
                tags="$tags,${image_name}:${tag_stable}";
              fi
            elif [ "${tag_type}" = "main" ]; then
              echo "main tag";
              tags="${image_name}:main-${tag_name}-${base}";
            elif [ "${tag_type}" = "devel" ]; then
              echo "devel tag";
              tags="${image_name}:devel-${tag_name}-${base}";
            elif [ "${tag_type}" = "feature" ]; then
              echo "feature tag";
              tags="${image_name}:feature-${tag_name}-${base}";
            fi
          fi
          echo "Building tags: ["${tags}"]"
          echo "RELEASE_TAGS=${tags}" >> $GITHUB_ENV
          echo "BASE_IMAGE=${select_base_image}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            USE_APT_PROXY=N
            BASE_IMAGE=${{ env.BASE_IMAGE }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: ${{ env.RELEASE_TAGS }}
